#!/usr/bin/env bash


## TODO reset
#02:18:03 ~ 0 $ cat /tmp/outs
#usage: ./wins < work | home | lap | focus>
#settings daemon overrides: @a{sv} {}
#gnome scaling factor: uint32 0
#gnome text-scaling factor: 1.0


set -e

# chrome UI size is using: text-scaling-factor
# gnome-shell UI is using: scaling-factor + xsettings overrides

show_scaling() {
  echo -n "settings daemon overrides: "
  gsettings get org.gnome.settings-daemon.plugins.xsettings overrides
  echo -n "gnome scaling factor: "
  gsettings get org.gnome.desktop.interface scaling-factor
  echo -n "gnome text-scaling factor: "
  gsettings get org.gnome.desktop.interface text-scaling-factor
}

_get_scaling() {
  gsettings get org.gnome.desktop.interface scaling-factor |
    sed 's/^uint32 *//; s/ *$//'
}

set_scaling() {
  local gdk_window_scaling="$1"
  local gnome_text_scaling_factor="$2"
  local gnome_scaling_factor="$3"
  local scaling_orig=$(_get_scaling)
  if [ "$gdk_window_scaling" ]; then
    gsettings set org.gnome.settings-daemon.plugins.xsettings \
              overrides "{'Gdk/WindowScalingFactor': <${gdk_window_scaling}>}"
  fi
  gsettings set org.gnome.desktop.interface \
            text-scaling-factor "$gnome_text_scaling_factor"
  gsettings set org.gnome.desktop.interface \
            scaling-factor "$gnome_scaling_factor"
  #if [ "$scaling_orig" != "$gnome_scaling_factor" ]; then
    #pkill -x gnome-shell
    #sleep 1
    #( gnome-shell --replace >/dev/null 2>&1 & disown )
    #sleep 2
  #fi
}

## BUG: seems this doesn't include decorations
_win_width() {
  xdotool getwindowgeometry "$1" |
    awk '/Geometry/ {split($2, x, "x"); print x[1]}'
}

_win_height() {
  xdotool getwindowgeometry "$1" |
    awk '/Geometry/ {split($2, x, "x"); print x[2]}'
}

_display_width() {
  xdotool getdisplaygeometry | awk '{print $1}'
}

_display_height() {
  xdotool getdisplaygeometry | awk '{print $2}'
}

_get_winid() {
  local class="$1"
  local win="$(xdotool search --class "^${class}$")"
  if [ -z "$win" ]; then
    echo "select '$class' window" >&2
    win="$(xdotool selectwindow)"
    if [ -z "$win" ]; then
      echo "failed to find '$class' win"; exit 1
    fi
    xdotool set_window --class "$class" "$win"
  fi
  echo "$win"
}



layout_large() {
  local ctxwin=$(_get_winid ctx)
  local _x=$(($(_display_width) - $(_win_width "$ctxwin") - 10))
  xdotool windowsize "$ctxwin" 26% 96% \
          windowmove "$ctxwin" "$_x" 35

  local devvmwin=$(_get_winid devvm)
  xdotool windowsize "$devvmwin" 72% 96% \
          windowmove "$devvmwin" 20 35

  #local chromepersonalwin=$(_get_winid chrome_personal)
  #xdotool windowsize "$chromepersonalwin" 45% 80%
  #xdotool windowmove "$chromepersonalwin" 350 200

  #local chromeworkwin=$(_get_winid chrome_work)
  #xdotool windowsize "$chromeworkwin" 60% 95%
  #xdotool windowmove "$chromeworkwin" 10 40
}


layout_small() {
  local ctxwin=$(_get_winid ctx)
  local _x=$(($(_display_width) - $(_win_width "$ctxwin") - 10))
  xdotool windowsize "$ctxwin" 34% 96% \
          windowmove "$ctxwin" "$_x" 50

  local devvmwin=$(_get_winid devvm)
  xdotool windowsize "$devvmwin" 65% 96% \
          windowmove "$devvmwin" 20 50

  #local chromepersonalwin=$(_get_winid chrome_personal)
  #xdotool windowsize "$chromepersonalwin" 85% 90%
  #xdotool windowmove "$chromepersonalwin" 100 100

  #local chromeworkwin=$(_get_winid chrome_work)
  #xdotool windowsize "$chromeworkwin" 85% 90%
  #xdotool windowmove "$chromeworkwin" 120 90
}


layout_focus() {
  win="$(xdotool selectwindow)"
  xdotool windowsize "$win" 50% 100%
  local _x=$(($(_display_width) / 4 - 60))
  xdotool windowmove "$win" "$_x" 0
}


## main
case "$1" in
  work) set_scaling 1 1 1; layout_large ;;
  home) set_scaling 1 1.5 1; layout_large ;;
  # high resolution but scale text, need to restart firefox to pickup change
  lap) set_scaling 1 1.5 1; layout_small ;;

  # Idealy only want to change text-scaling-factor but requires firefox restart
  # this adjusts 2x gdk scaling firefox but gnome window decorations look ugly
  lap-2x) set_scaling 2 1 1; layout_small ;;

  # this adjusts 2x gdk scaling firefox + adjusts windows decor
  # but requires restarting gnome-shell which is invasive
  lap-2x-rescale) set_scaling 2 1 2; layout_small ;;

  xx) set_scaling '' 0 1; layout_small ;;

  focus) layout_focus ;;
  *)
    echo -e "usage: $0 < work | home | lap | focus>" >&2
    show_scaling >&2
    ;;

esac
